stages:
  prepare:
    cmd: python -m src.data
    deps:
      - data/raw/data.csv
      - src/data.py
      - configs/train_config.yaml
    outs:
      - data/processed/train.parquet
      - data/processed/test.parquet

  train:
    cmd: python -m src.train
    deps:
      - data/processed/train.parquet
      - data/processed/test.parquet
      - src/train.py
      - configs/train_config.yaml
